name = "xyBnG"
uuid = "056de5cc-3822-4b22-85ae-bc65d3fbfd0e"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
